platform :ios, '9.0'
use_frameworks!

target 'HotSpot' do
    pod 'SwiftHEXColors', :git => 'https://github.com/thii/SwiftHEXColors.git', :branch => 'swift-3.0'
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
    pod 'SimpleAnimation'
    pod 'SwiftyJSON', :git => 'https://github.com/IBM-Swift/SwiftyJSON.git'
    pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :branch => 'swift3'
end
